# Generated by Django 5.2.3 on 2025-06-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_approvedstudent_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedstudent',
            name='classes',
            field=models.CharField(choices=[('1-4', 'classes 1 to 4'), ('5-8', 'classes 5 to 8'), ('9-10', 'classes 9 to 10'), ('11-12', 'classes 11 to 12')], max_length=20),
        ),
    ]
